services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: atigacbt
      POSTGRES_USER: atigacbt
      POSTGRES_PASSWORD: atigacbt
    ports:
      - "5433:5432"
    volumes:
      - atigacbt_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "redisStrongPass123!"]
    ports:
      - "6379:6379"
    volumes:
      - atigacbt_redisdata:/data

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - atigacbt_rustfs_data:/data
      - atigacbt_rustfs_logs:/logs

volumes:
  atigacbt_pgdata:
  atigacbt_redisdata:
  atigacbt_rustfs_data:
  atigacbt_rustfs_logs:
