services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mycbt
      POSTGRES_USER: mycbt
      POSTGRES_PASSWORD: mycbt
    ports:
      - "5433:5432"
    volumes:
      - mycbt_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - mycbt_redisdata:/data

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mycbt_rustfs_data:/data
      - mycbt_rustfs_logs:/logs

volumes:
  mycbt_pgdata:
  mycbt_redisdata:
  mycbt_rustfs_data:
  mycbt_rustfs_logs:
