name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: latest
      build_backend:
        description: 'Build and push backend image'
        type: boolean
        required: true
        default: false
      build_frontend:
        description: 'Build and push frontend image'
        type: boolean
        required: true
        default: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.image_tag || 'latest' }}
      FRONTEND_IMAGE: ghcr.io/${{ github.repository_owner }}/atigacbt-frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend
        if: ${{ github.event_name == 'push' || inputs.build_frontend == true }}
        run: docker build -t $FRONTEND_IMAGE:$IMAGE_TAG -f docker/frontend.Dockerfile .

      - name: Push Frontend
        if: ${{ github.event_name == 'push' || inputs.build_frontend == true }}
        run: docker push $FRONTEND_IMAGE:$IMAGE_TAG

  build-backend:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.build_backend == true }}
    env:
      IMAGE_TAG: ${{ inputs.image_tag || 'latest' }}
      BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/atigacbt-backend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Backend
        run: docker build -t $BACKEND_IMAGE:$IMAGE_TAG -f docker/backend.Dockerfile .

      - name: Push Backend
        run: docker push $BACKEND_IMAGE:$IMAGE_TAG
